### ISSUE TITLE
email field modify input

### ISSUE THREAD

**Issue by tianroy** [MagicCube/x-challenge-club#10]
##![image](https://cloud.githubusercontent.com/assets/20764962/17284691/99e101f4-57ef-11e6-9674-2f4979823e71.png)
Type test@test.com
Then move your pointer in the middle of test and @
Type 123 in the middle then the display will be wrong

**Comment by tianroy** [comment]
Happens on iOS

**Comment by vipulprajapati6584** [comment]
Fixed
