### ISSUE TITLE
Where's the dropdown arrow

### ISSUE THREAD

**Issue by MagicCube** [MagicCube/x-challenge-club#4]
![image](https://cloud.githubusercontent.com/assets/1003147/17243222/0bbcdfbc-55ae-11e6-98df-54153db3b57c.png)

After click on the dropdown and switch to China
The dropdown arrow will disappear

![image](https://cloud.githubusercontent.com/assets/1003147/17243245/36e21f2c-55ae-11e6-8458-67e56af22e44.png)

**Comment by vipulprajapati6584** [comment]
Fixed

**Comment by MagicCube** [comment]
great
